#!/usr/bin/env python3
"""modal_builder.py — write a two-phase modal_app.py from a compact JSON spec.
Called by the `run-on-modal` skill (script-offloading, workbench-conventions §9):
the skill profiles hardware + picks a GPU tier, this script writes every byte of the
Modal decorator boilerplate — the CPU download_data() function, the GPU
run_experiment() function, the local_entrypoint that sequences them, the Image build,
the cost header, and the quick-start block. The model never hand-writes the envelope.

Usage:
    python modal_builder.py .tmp/run-on-modal_<id>_<mode>.json [--out-root modal_apps]

Output: modal_apps/<id>-<mode>/modal_app.py
"""
from __future__ import annotations

import argparse
import json
import sys
import textwrap
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass


def _indent(body: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + ln if ln.strip() else ln for ln in body.split("\n"))


def build_app(spec: dict) -> str:
    pid = spec["paper_id"]
    mode = spec.get("mode", "run-results")
    app_name = spec.get("app_name", f"paper-{pid}-{mode}")
    gpu = spec.get("gpu", "A100-40GB")
    gpu_count = int(spec.get("gpu_count", 1))
    gpu_spec = f"{gpu}:{gpu_count}" if gpu_count > 1 else gpu
    timeout = int(spec.get("timeout", 3600))
    py = spec.get("python_version", "3.11")
    deps = spec.get("dependencies") or []
    apt = spec.get("apt_packages") or []
    run_cmds = spec.get("run_commands") or []
    repo = spec.get("repo_url")
    hf_repo = spec.get("hf_repo")
    needs_hf = bool(spec.get("needs_hf_token"))
    volumes = spec.get("volumes") or [{"name": f"paper-{pid}-data", "mount": "/data"}]
    vol = volumes[0]
    datasets = spec.get("dataset_files") or []
    weights = spec.get("weight_files") or []
    exp_body = spec.get("experiment_body", "# TODO: run the experiment; read inputs from "
                        + vol["mount"] + "\nprint('experiment placeholder')")
    cost = spec.get("cost_estimate") or {}
    vram = spec.get("vram_estimate", "not estimated")
    manual = spec.get("manual_steps") or []

    # --- header comment (cost + quick-start) ---
    cost_line = ""
    if cost:
        cost_line = (f"#   est: {cost.get('gpu', gpu)} x {cost.get('est_hours','?')}h "
                     f"@ ${cost.get('price_per_hr','?')}/h = ${cost.get('est_cost','?')}")
    manual_block = "".join(f"#   - {m}\n" for m in manual)
    header = textwrap.dedent(f'''\
        # modal_app.py — paper {pid} ({mode}) — generated by run-on-modal
        # GPU tier: {gpu_spec}   VRAM estimate: {vram}
        {cost_line}
        #
        # Quick start:
        #   pip install modal
        #   modal token new          # one-time auth
        #   modal run modal_app.py   # runs download_data() then run_experiment()
        #
        # Manual steps:
        {manual_block}''')

    # --- image build chain ---
    img = f'modal.Image.debian_slim(python_version="{py}")'
    if apt:
        img += f'\n    .apt_install({", ".join(repr(a) for a in apt)})'
    if deps:
        img += f'\n    .pip_install({", ".join(repr(d) for d in deps)})'
    if needs_hf:
        img += '\n    .pip_install("huggingface_hub")'
    for cmd in run_cmds:
        img += f'\n    .run_commands({cmd!r})'
    if repo:
        img += f'\n    .run_commands("git clone --depth 1 {repo} /repo")'

    # --- download body ---
    dl_lines = ["import os, urllib.request",
                "from concurrent.futures import ThreadPoolExecutor",
                f'os.makedirs("{vol["mount"]}", exist_ok=True)', "targets = ["]
    for d in datasets + weights:
        dl_lines.append(f'    ("{vol["mount"]}/{d["name"]}", "{d["url"]}"),')
    dl_lines.append("]")
    dl_lines += [
        "def _fetch(t):",
        "    dest, url = t",
        "    if os.path.exists(dest):",
        "        return f'cached {dest}'",
        "    urllib.request.urlretrieve(url, dest)",
        "    return f'downloaded {dest}'",
        "with ThreadPoolExecutor(max_workers=4) as ex:",
        "    for r in ex.map(_fetch, targets):",
        "        print(r)",
    ]
    if hf_repo:
        dl_lines += [
            "from huggingface_hub import snapshot_download",
            f'snapshot_download(repo_id="{hf_repo}", local_dir="{vol["mount"]}/hf")',
        ]
    dl_lines.append("vol.commit()  # persist downloads for the GPU function")
    dl_body = "\n".join(dl_lines)

    secrets = ""
    if needs_hf:
        secrets = ', secrets=[modal.Secret.from_name("huggingface")]'

    app = f'''{header}
import modal

app = modal.App("{app_name}")

image = (
    {img}
)

vol = modal.Volume.from_name("{vol["name"]}", create_if_missing=True)


@app.function(image=image, volumes={{"{vol["mount"]}": vol}}, timeout={timeout})
def download_data():
    """Phase 1 — CPU only (no GPU billing). Idempotent; commits to the Volume."""
{_indent(dl_body, 4)}


@app.function(image=image, gpu="{gpu_spec}", volumes={{"{vol["mount"]}": vol}}, timeout={timeout}{secrets})
def run_experiment():
    """Phase 2 — GPU. Reads inputs from the Volume at {vol["mount"]}."""
    import torch
    print("CUDA:", torch.cuda.is_available(),
          torch.cuda.get_device_name(0) if torch.cuda.is_available() else "")
{_indent(exp_body, 4)}


@app.local_entrypoint()
def main():
    download_data.remote()   # phase 1: fetch on CPU
    run_experiment.remote()  # phase 2: compute on GPU
'''
    return app


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("spec", type=Path)
    ap.add_argument("--out-root", type=Path, default=Path("modal_apps"))
    args = ap.parse_args()

    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    for k in ("paper_id", "mode"):
        if k not in spec:
            sys.exit(f"[modal_builder] spec missing required key: {k!r}")
    out_dir = args.out_root / f"{spec['paper_id']}-{spec['mode']}"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / "modal_app.py"
    out.write_text(build_app(spec), encoding="utf-8")
    print(json.dumps({"modal_app": str(out), "gpu": spec.get("gpu"),
                      "mode": spec["mode"]}, ensure_ascii=False))


if __name__ == "__main__":
    main()
