#!/usr/bin/env python3
"""nb_builder.py — assemble a runnable Jupyter notebook (.ipynb) from a compact JSON
spec. Called by the `paper-to-notebook` skill (script-offloading,
workbench-conventions §9): the skill emits facts + per-stage cells, this script
writes every byte of nbformat JSON boilerplate (GPU check, pip install, parallel
downloader, repo clone, the section-annotated cells, and — for run-results — a
results-vs-paper comparison cell). The model never hand-writes notebook structure.

Usage:
    python nb_builder.py .tmp/paper-to-notebook_<id>_<mode>.json [--out-dir notebooks]

Spec schema:
    {
      "paper_id": "003", "title": "...", "mode": "reproduce" | "run-results",
      "repo_url": "https://github.com/... " | null,
      "dependencies": ["torch", "torchvision"],
      "apt_packages": ["ffmpeg"],                          # optional
      "dataset_files": [{"name": "ava.zip", "url": "https://..."}],
      "weight_files":  [{"name": "model.pth", "url": "https://..."}],
      "hf_repo": "org/model" | null, "needs_hf_token": false,
      "reported_results": [{"metric": "Spearman rho", "paper": 0.78}],  # run-results
      "sections": [
        {"kind": "markdown"|"code", "title": "Stage 1 — ...",
         "paper_ref": "§3.2 / Eq. 4", "body": "..."}
      ],
      "manual_steps": ["Accept the dataset license at ...", "..."]
    }

Output: notebooks/<id>-<mode>.ipynb
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _lines(text)}


def code(text: str) -> dict:
    return {"cell_type": "code", "metadata": {}, "execution_count": None,
            "outputs": [], "source": _lines(text)}


def _lines(text: str) -> list[str]:
    """nbformat wants a list of lines, each ending in \\n except possibly the last."""
    parts = text.split("\n")
    return [p + "\n" for p in parts[:-1]] + ([parts[-1]] if parts[-1] else [])


def build(spec: dict) -> dict:
    pid = spec["paper_id"]
    title = spec.get("title", "")
    mode = spec.get("mode", "reproduce")
    cells: list[dict] = []

    # --- Header ---
    cells.append(md(
        f"# {title}\n\n"
        f"**Paper id:** {pid} · **Mode:** `{mode}` · generated by `paper-to-notebook`\n\n"
        f"This notebook { 'reproduces the method' if mode == 'reproduce' else 'runs the published evaluation with pretrained weights' } "
        f"for paper {pid}. Cells are annotated with the paper section they implement.\n\n"
        f"> Runs on Colab or locally. Check the **Environment** cell first for GPU + deps."
    ))

    # --- Manual steps banner ---
    manual = spec.get("manual_steps") or []
    if manual:
        steps = "\n".join(f"{i+1}. {s}" for i, s in enumerate(manual))
        cells.append(md(f"## ⚠️ Manual steps before running\n\n{steps}"))

    # --- Environment / GPU check ---
    cells.append(md("## Environment"))
    cells.append(code(
        "import sys, subprocess, importlib\n"
        "print('Python', sys.version.split()[0])\n"
        "try:\n"
        "    import torch\n"
        "    print('CUDA available:', torch.cuda.is_available())\n"
        "    if torch.cuda.is_available():\n"
        "        print('GPU:', torch.cuda.get_device_name(0))\n"
        "except ImportError:\n"
        "    print('torch not yet installed — see the install cell below')"
    ))

    # --- apt + pip install ---
    apt = spec.get("apt_packages") or []
    deps = spec.get("dependencies") or []
    install_lines = []
    if apt:
        install_lines.append(f"!apt-get -qq install -y {' '.join(apt)}")
    if deps:
        install_lines.append(f"!pip -q install {' '.join(deps)}")
    if spec.get("needs_hf_token"):
        install_lines.append("!pip -q install huggingface_hub")
    if install_lines:
        cells.append(code("\n".join(install_lines)))

    # --- HF login (gated weights) ---
    if spec.get("needs_hf_token"):
        cells.append(md("### Hugging Face token (gated repo)"))
        cells.append(code(
            "from huggingface_hub import login\n"
            "import os\n"
            "# Set HF_TOKEN in the environment, or paste it when prompted.\n"
            "login(token=os.environ.get('HF_TOKEN'))"
        ))

    # --- Clone repo ---
    repo = spec.get("repo_url")
    if repo:
        cells.append(md(f"## Official code\n\nCloning `{repo}`."))
        cells.append(code(f"!git clone --depth 1 {repo} repo\n%cd repo"))

    # --- Parallel downloader (datasets + weights) ---
    downloads = []
    for d in (spec.get("dataset_files") or []):
        downloads.append((d["name"], d["url"], "data"))
    for w in (spec.get("weight_files") or []):
        downloads.append((w["name"], w["url"], "weights"))
    hf_repo = spec.get("hf_repo")
    if downloads or hf_repo:
        cells.append(md("## Download data & weights (parallel)"))
    if downloads:
        items = ",\n    ".join(f'("{n}", "{u}", "{d}")' for n, u, d in downloads)
        cells.append(code(
            "import os, urllib.request\n"
            "from concurrent.futures import ThreadPoolExecutor\n\n"
            "DOWNLOADS = [\n    " + items + ",\n]\n\n"
            "def _fetch(item):\n"
            "    name, url, sub = item\n"
            "    os.makedirs(sub, exist_ok=True)\n"
            "    dest = os.path.join(sub, name)\n"
            "    if os.path.exists(dest):\n"
            "        return f'cached {dest}'\n"
            "    urllib.request.urlretrieve(url, dest)\n"
            "    return f'downloaded {dest}'\n\n"
            "with ThreadPoolExecutor(max_workers=4) as ex:\n"
            "    for r in ex.map(_fetch, DOWNLOADS):\n"
            "        print(r)"
        ))
    if hf_repo:
        cells.append(code(
            "from huggingface_hub import snapshot_download\n"
            f"path = snapshot_download(repo_id='{hf_repo}')\n"
            "print('weights at', path)"
        ))

    # --- Method / eval sections (model-provided) ---
    for sec in (spec.get("sections") or []):
        ref = f" *(paper {sec['paper_ref']})*" if sec.get("paper_ref") else ""
        if sec.get("kind") == "markdown":
            cells.append(md(f"## {sec.get('title','')}{ref}\n\n{sec.get('body','')}"))
        else:
            header = f"# {sec.get('title','')}{(' — paper ' + sec['paper_ref']) if sec.get('paper_ref') else ''}\n"
            cells.append(code(header + sec.get("body", "")))

    # --- run-results: comparison cell with delta-flag (tolerance-gated) ---
    if mode == "run-results" and spec.get("reported_results"):
        rows = spec["reported_results"]
        rep = ",\n    ".join(f'("{r["metric"]}", {r["paper"]})' for r in rows)
        # Tolerance is optional; defaults keep the old behavior + add the flag column.
        tol = spec.get("tolerance", {"match": 0.5, "close": 1.0})
        tol_match = tol.get("match", 0.5)
        tol_close = tol.get("close", 1.0)
        cells.append(md(
            "## Results vs paper\n\n"
            "Fill `produced` from the eval output above, then run this cell to compare "
            "against the paper's reported numbers. Each metric gets a flag:\n"
            f"- `match` — |Δ| ≤ {tol_match}\n"
            f"- `close` — {tol_match} < |Δ| ≤ {tol_close} (note environment)\n"
            f"- `diverge` — |Δ| > {tol_close} (investigate: seed / hardware / "
            "preprocessing version / subset vs full eval)\n"
            "- `missing` — paper reports it, you did not reproduce it (NOT fabricated).\n\n"
            "Do NOT round or adjust reproduced numbers to match the paper."))
        cells.append(code(
            "reported = [\n    " + rep + ",\n]\n"
            f"TOL_MATCH, TOL_CLOSE = {tol_match}, {tol_close}\n"
            "produced = {}  # e.g. {'Spearman rho': 0.77}\n\n"
            "def flag(paper_val, ours):\n"
            "    if ours is None:\n"
            "        return 'missing'\n"
            "    d = abs(ours - paper_val)\n"
            "    if d <= TOL_MATCH:\n"
            "        return 'match'\n"
            "    return 'close' if d <= TOL_CLOSE else 'diverge'\n\n"
            "hdr = f\"{'metric':24} {'paper':>8} {'ours':>8} {'delta':>9} {'flag':>9}\"\n"
            "print(hdr)\n"
            "for metric, paper_val in reported:\n"
            "    ours = produced.get(metric)\n"
            "    delta = '' if ours is None else f'{ours - paper_val:+.4f}'\n"
            "    fg = flag(paper_val, ours)\n"
            "    print(f'{metric:24} {paper_val:>8} {str(ours):>8} {delta:>9} {fg:>9}')"
        ))

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
            "paper_id": pid, "mode": mode,
        },
        "nbformat": 4, "nbformat_minor": 5,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("spec", type=Path)
    ap.add_argument("--out-dir", type=Path, default=Path("notebooks"))
    args = ap.parse_args()

    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    for k in ("paper_id", "mode"):
        if k not in spec:
            sys.exit(f"[nb_builder] spec missing required key: {k!r}")
    args.out_dir.mkdir(parents=True, exist_ok=True)
    nb = build(spec)
    out = args.out_dir / f"{spec['paper_id']}-{spec['mode']}.ipynb"
    out.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
    print(json.dumps({"notebook": str(out), "cells": len(nb["cells"]),
                      "mode": spec["mode"]}, ensure_ascii=False))


if __name__ == "__main__":
    main()
